#!/bin/sh

set -e

if [ ! -d "./rstudio" ]; then
   git clone git@github.com:rstudio/rstudio.git
fi

cd rstudio
git checkout master
git pull

# copy resoruces files
RESOURCES_DIR=src/cpp/session/resources
HTML_DIR=../markdown/inst/resources
cp $RESOURCES_DIR/markdown.html $HTML_DIR
cp $RESOURCES_DIR/markdown.css $HTML_DIR
cp $RESOURCES_DIR/r_highlight.html $HTML_DIR
cp $RESOURCES_DIR/mathjax.html $HTML_DIR

# copy R source files
MODULES_DIR=src/cpp/session/modules
R_SRC_DIR=../markdown/R
cp $MODULES_DIR/SessionRPubs.R $R_SRC_DIR/rpubsUpload.R

# roxygenize
cd ../markdown
make
