#!/bin/sh

set -e

if [ ! -d "./sundown" ]; then
   git clone git@github.com:rstudio/sundown.git
fi

cd sundown
git clean -dfx

# Use the branch with rstudio-specific changes 
git checkout master
git pull
VERSION=`git rev-parse HEAD`

# copy files
MARKDOWN_DIR=../..
echo "#define RSTUDIO_SUNDOWN_VERSION $VERSION" > src/sundown_version.h
cp src/autolink.h $MARKDOWN_DIR/inst/include
cp src/buffer.h $MARKDOWN_DIR/inst/include
cp src/markdown.h $MARKDOWN_DIR/inst/include
cp src/*.h $MARKDOWN_DIR/src
cp src/*.c $MARKDOWN_DIR/src
cp html/*.h $MARKDOWN_DIR/src
cp html/*.c $MARKDOWN_DIR/src

# return to tools dir
cd ..
